name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This assumes your HTML, CSS, and JS files are in the root directory
          publish_branch: gh-pages  # Specify the branch for GitHub Pages
